# Init
spring.application.name=app_save
spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cloudinary
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_KEY}
cloudinary.api_secret=${CLOUD_SECRET}

# Seguridad
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

# JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${PRIVATE_USER}
security.jwt.expiration.time=900000
