# Init
spring.application.name=app_save
spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://app_s:3307/save_food?createDatabaseIfNotExist=true&serverTimezone=UTC

spring.datasource.username=srtaliv
spring.datasource.password=bardovich712
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuraci�n Cloudinary
cloudinary.cloud_name=${CLOUD_NAME:dsnnaq4iz}
cloudinary.api_key=${CLOUD_KEY:796817321694386}
cloudinary.api_secret=${CLOUD_SECRET:qqqbQflJptyijfCGneLrymBEzeY}

# Configuraci�n de seguridad
spring.security.user.name=${SS_USER:root}
spring.security.user.password=${SS_PASSWORD:wachiturro712}

# Configuraci�n JWT
security.jwt.private.key=${PRIVATE_KEY:4810eb165b0df3591cb8702cc026ff9f3bec16e487abd200519e52690b93c954}
security.jwt.user.generator=${PRIVATE_USER:bardovich}
security.jwt.expiration.time=900000